/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author SENITH
 */
public class OrderFromSuppUI extends javax.swing.JFrame {

    /**
     * Creates new form OrderFromSuppUI
     */
    public OrderFromSuppUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtInsType = new javax.swing.JComboBox<>();
        txtAccType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtInsQ = new javax.swing.JTextField();
        txtAccQ = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSupplier = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtAIQ = new javax.swing.JTextField();
        txtAAQ = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Order From Suppliers");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(495, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Accessories Type");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Instrument Type");

        txtInsType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guiter", "Drumset", "Violin", "Piano" }));

        txtAccType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drumset Chair", "Drumset Stick", "Guitar Pick", "Guitar Strings", "Piano Chair", "Violin Strings" }));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Avaliable");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("From");

        txtSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier 1", "Supplier 2", "Supplier 3" }));

        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantity");

        jButton3.setText("Show Avaliability");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jButton2))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInsType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAccType, 0, 226, Short.MAX_VALUE)
                            .addComponent(txtSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtAccQ, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAAQ, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtInsQ, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txtAIQ, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(533, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInsType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAIQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAAQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(42, 42, 42)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(jLabel8)
                    .addContainerGap(287, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminMenuUI m = new AdminMenuUI();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver");//com.microsoft.sqlserver.jdbc.SQLServerDriver
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/music_mart", "root", "");
            String itemSelect = txtInsType.getSelectedItem() + "";
            if (itemSelect.equals("Guiter")) {
                String a = txtInsQ.getText();
                int qunI = Integer.parseInt(a);

                String query1 = "update instrument set InsQuantity =InsQuantity+" + qunI + " where InsID=1";
                PreparedStatement p1 = con.prepareStatement(query1);
                p1.execute();

            } else if (itemSelect.equals("Drumset")) {
                String a = txtInsQ.getText();
                int qunI = Integer.parseInt(a);
                String query1 = "update instrument set InsQuantity =InsQuantity+" + qunI + " where InsID=2";
                PreparedStatement p1 = con.prepareStatement(query1);
                p1.execute();

            } else if (itemSelect.equals("Violin")) {
                String a = txtInsQ.getText();
                int qunI = Integer.parseInt(a);
                String query1 = "update instrument set InsQuantity =InsQuantity+" + qunI + " where InsID=3";
                PreparedStatement p1 = con.prepareStatement(query1);
                p1.execute();

            } else if (itemSelect.equals("Piano")) {
                String a = txtInsQ.getText();
                int qunI = Integer.parseInt(a);
                String query1 = "update instrument set InsQuantity =InsQuantity+" + qunI + " where InsID=4";
                PreparedStatement p1 = con.prepareStatement(query1);
                p1.execute();

            }

        } catch (Exception e) {

        }

         try {

            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver");//com.microsoft.sqlserver.jdbc.SQLServerDriver
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/music_mart", "root", "");
            
            String itemSelect = txtAccType.getSelectedItem() + "";
            

            if (itemSelect.equals("Drumset Chair")) {

                int qunA = Integer.parseInt(txtAccQ.getText());
                String query1 = "update accessories set AccQuantity =AccQuantity+" + qunA + " where AccID=1";
                PreparedStatement p1 = con.prepareStatement(query1);
                p1.execute();

            }else if (itemSelect.equals("Drumset Stick")) {
                int qunA = Integer.parseInt(txtAccQ.getText());
                String query1 = "update accessories set AccQuantity =AccQuantity+" + qunA + " where AccID=2";
                PreparedStatement p1 = con.prepareStatement(query1);
                p1.execute();

            }else if (itemSelect.equals("Guitar Pick")) {
                int qunA = Integer.parseInt(txtAccQ.getText());
                String query1 = "update accessories set AccQuantity =AccQuantity+" + qunA + " where AccID=3";
                PreparedStatement p1 = con.prepareStatement(query1);
                p1.execute();

            }else if (itemSelect.equals("Guitar Strings")) {
                int qunA = Integer.parseInt(txtAccQ.getText());
                String query1 = "update accessories set AccQuantity =AccQuantity+" + qunA + " where AccID=4";
                PreparedStatement p1 = con.prepareStatement(query1);
                p1.execute();

            }else if (itemSelect.equals("Piano Chair")) {
                int qunA = Integer.parseInt(txtAccQ.getText());
                String query1 = "update accessories set AccQuantity =AccQuantity+" + qunA + " where AccID=5";
                PreparedStatement p1 = con.prepareStatement(query1);
                p1.execute();

            }else if (itemSelect.equals("Violin Strings")) {
                int qunA = Integer.parseInt(txtAccQ.getText());
                String query1 = "update accessories set AccQuantity =AccQuantity+" + qunA + " where AccID=6";
                PreparedStatement p1 = con.prepareStatement(query1);
                p1.execute();

            }

        } catch (Exception e) {

        }
         JOptionPane.showMessageDialog(rootPane, "Order Successful", "Sucess", 1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver");//com.microsoft.sqlserver.jdbc.SQLServerDriver
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/music_mart", "root", "");
            String itemSelect = txtInsType.getSelectedItem() + "";
            if (itemSelect.equals("Guiter")) {
                

                String query1 = "select InsQuantity from instrument where InsID=1";
                PreparedStatement p1 = con.prepareStatement(query1);
                ResultSet rs = p1.executeQuery();
                if(rs.next())
                {
                    String a=String.valueOf(rs.getInt("InsQuantity"));
                    txtAIQ.setText(a);

                }
                
            } else if (itemSelect.equals("Drumset")) {
                String query1 = "select InsQuantity from instrument where InsID=2";
                PreparedStatement p1 = con.prepareStatement(query1);
                ResultSet rs = p1.executeQuery();
                if(rs.next())
                {
                    String a=String.valueOf(rs.getInt("InsQuantity"));
                    txtAIQ.setText(a);

                }
                
            } else if (itemSelect.equals("Violin")) {
                String query1 = "select InsQuantity from instrument where InsID=3";
                PreparedStatement p1 = con.prepareStatement(query1);
                ResultSet rs = p1.executeQuery();
                if(rs.next())
                {
                    String a=String.valueOf(rs.getInt("InsQuantity"));
                    txtAIQ.setText(a);

                }
                
            } else if (itemSelect.equals("Piano")) {
                String query1 = "select InsQuantity from instrument where InsID=4";
                PreparedStatement p1 = con.prepareStatement(query1);
                ResultSet rs = p1.executeQuery();
                if(rs.next())
                {
                    String a=String.valueOf(rs.getInt("InsQuantity"));
                    txtAIQ.setText(a);

                }
                
            }

        } catch (Exception e) {

        }

         try {

            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver");//com.microsoft.sqlserver.jdbc.SQLServerDriver
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/music_mart", "root", "");
            
            String itemSelect = txtAccType.getSelectedItem() + "";
            

            if (itemSelect.equals("Drumset Chair")) {
                String query1 = "select AccQuantity from accessories where AccID=1";
                PreparedStatement p1 = con.prepareStatement(query1);
                ResultSet rs = p1.executeQuery();
                if(rs.next())
                {
                    String a=String.valueOf(rs.getInt("AccQuantity"));
                    txtAAQ.setText(a);

                }


            }else if (itemSelect.equals("Drumset Stick")) {
                String query1 = "select AccQuantity from accessories where AccID=2";
                PreparedStatement p1 = con.prepareStatement(query1);
                ResultSet rs = p1.executeQuery();
                if(rs.next())
                {
                    String a=String.valueOf(rs.getInt("AccQuantity"));
                    txtAAQ.setText(a);

                }

            }else if (itemSelect.equals("Guitar Pick")) {
                String query1 = "select AccQuantity from accessories where AccID=3";
                PreparedStatement p1 = con.prepareStatement(query1);
                ResultSet rs = p1.executeQuery();
                if(rs.next())
                {
                    String a=String.valueOf(rs.getInt("AccQuantity"));
                    txtAAQ.setText(a);

                }

            }else if (itemSelect.equals("Guitar Strings")) {
                String query1 = "select AccQuantity from accessories where AccID=4";
                PreparedStatement p1 = con.prepareStatement(query1);
                ResultSet rs = p1.executeQuery();
                if(rs.next())
                {
                    String a=String.valueOf(rs.getInt("AccQuantity"));
                    txtAAQ.setText(a);

                }

            }else if (itemSelect.equals("Piano Chair")) {
               String query1 = "select AccQuantity from accessories where AccID=5";
                PreparedStatement p1 = con.prepareStatement(query1);
                ResultSet rs = p1.executeQuery();
                if(rs.next())
                {
                    String a=String.valueOf(rs.getInt("AccQuantity"));
                    txtAAQ.setText(a);

                }

            }else if (itemSelect.equals("Violin Strings")) {
                String query1 = "select AccQuantity from accessories where AccID=6";
                PreparedStatement p1 = con.prepareStatement(query1);
                ResultSet rs = p1.executeQuery();
                if(rs.next())
                {
                    String a=String.valueOf(rs.getInt("AccQuantity"));
                    txtAAQ.setText(a);

                }

            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFromSuppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFromSuppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFromSuppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFromSuppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFromSuppUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtAAQ;
    private javax.swing.JTextField txtAIQ;
    private javax.swing.JTextField txtAccQ;
    private javax.swing.JComboBox<String> txtAccType;
    private javax.swing.JTextField txtInsQ;
    private javax.swing.JComboBox<String> txtInsType;
    private javax.swing.JComboBox<String> txtSupplier;
    // End of variables declaration//GEN-END:variables
}
